/**
 * Marvel Omniverse Nexus - Encyclopedic Marvel Database
 * Comprehensive structured database of MCU Movies, Iconic Comic Storylines, Character Dossiers & Comic Runs.
 */

const MARVEL_DATA = {
    movies: [
        {
            id: "iron-man-1",
            title: "Iron Man",
            type: "movie",
            phase: "Phase 1",
            saga: "The Infinity Saga",
            releaseYear: 2008,
            chronologicalOrder: 3,
            chronologicalYear: "2010",
            duration: "126 min",
            director: "Jon Favreau",
            synopsis: "Billionaire genius Tony Stark is kidnapped in Afghanistan and builds an armored suit to escape. Back home, he refines the technology to fight terrorism and stop his mentor Obadiah Stane, who seeks to weaponize the technology.",
            comicInspiration: "Tales of Suspense #39 (1963) and Warren Ellis's 'Extremis' arc (Iron Man Vol. 4 #1-6, 2005).",
            mainVillain: "Obadiah Stane / Iron Monger",
            keyCharacters: ["Tony Stark / Iron Man", "Pepper Potts", "James Rhodes", "Obadiah Stane", "J.A.R.V.I.S.", "Nick Fury"],
            postCredits: "Nick Fury steps out of the shadows to introduce the 'Avengers Initiative'.",
            boxOffice: "$585.8 Million",
            rating: "8.0/10",
            trivia: "Robert Downey Jr. often improvised dialogue, and the script didn't have all scenes finalized before shooting.",
            tags: ["Iron Man", "Tony Stark", "Origins", "Phase 1", "Stark Industries", "Avengers Initiative"]
        },
        {
            id: "captain-america-1",
            title: "Captain America: The First Avenger",
            type: "movie",
            phase: "Phase 1",
            saga: "The Infinity Saga",
            releaseYear: 2011,
            chronologicalOrder: 1,
            chronologicalYear: "1942 - 1945",
            duration: "124 min",
            director: "Joe Johnston",
            synopsis: "During World War II, frail Steve Rogers volunteers for a top-secret super-soldier experiment. Transformed into Captain America, he battles HYDRA and its ruthless leader, the Red Skull, who harnesses the mysterious Tesseract (Space Stone).",
            comicInspiration: "Captain America Comics #1 (1941) by Joe Simon and Jack Kirby.",
            mainVillain: "Johann Schmidt / Red Skull",
            keyCharacters: ["Steve Rogers / Captain America", "Peggy Carter", "Bucky Barnes", "Red Skull", "Howard Stark", "Dr. Abraham Erskine"],
            postCredits: "Steve Rogers awakens in modern-day Times Square, greeted by Nick Fury.",
            boxOffice: "$370.6 Million",
            rating: "7.0/10",
            trivia: "Chris Evans declined the role three times due to anxiety about long-term franchise commitment before accepting.",
            tags: ["Captain America", "Steve Rogers", "HYDRA", "Tesseract", "Infinity Stone", "Phase 1", "WWII"]
        },
        {
            id: "the-avengers",
            title: "The Avengers",
            type: "movie",
            phase: "Phase 1",
            saga: "The Infinity Saga",
            releaseYear: 2012,
            chronologicalOrder: 6,
            chronologicalYear: "2012",
            duration: "143 min",
            director: "Joss Whedon",
            synopsis: "When Thor's adoptive brother Loki gains access to the Tesseract and leads a Chitauri invasion in New York, S.H.I.E.L.D. director Nick Fury activates the Avengers Initiative, uniting Earth's mightiest heroes for the first time.",
            comicInspiration: "The Avengers #1 (1963) and Mark Millar & Bryan Hitch's 'The Ultimates' (2002).",
            mainVillain: "Loki (commanding the Chitauri Army)",
            keyCharacters: ["Tony Stark", "Steve Rogers", "Thor", "Bruce Banner / Hulk", "Natasha Romanoff / Black Widow", "Clint Barton / Hawkeye", "Loki", "Nick Fury"],
            postCredits: "The Other warns Thanos that challenging humans is to 'court death'; Thanos turns to the camera with a sinister grin.",
            boxOffice: "$1.520 Billion",
            rating: "8.0/10",
            trivia: "First Marvel movie to cross $1 billion. The iconic shawarma scene was filmed the day after the global premiere.",
            tags: ["Avengers", "Battle of New York", "Loki", "Thanos", "Tesseract", "Phase 1", "Infinity Saga"]
        },
        {
            id: "captain-america-winter-soldier",
            title: "Captain America: The Winter Soldier",
            type: "movie",
            phase: "Phase 2",
            saga: "The Infinity Saga",
            releaseYear: 2014,
            chronologicalOrder: 9,
            chronologicalYear: "2014",
            duration: "136 min",
            director: "Anthony and Joe Russo",
            synopsis: "Steve Rogers struggles to adapt to the modern world while uncovering a deep conspiracy inside S.H.I.E.L.D., orchestrated by a resurgent HYDRA. He faces a deadly brainwashed Soviet assassin with a cybernetic arm: his long-lost friend Bucky Barnes.",
            comicInspiration: "Ed Brubaker and Steve Epting's landmark 'Captain America: The Winter Soldier' comic arc (2005).",
            mainVillain: "Alexander Pierce & The Winter Soldier (Bucky Barnes)",
            keyCharacters: ["Steve Rogers", "Natasha Romanoff", "Sam Wilson / Falcon", "Bucky Barnes", "Nick Fury", "Alexander Pierce"],
            postCredits: "Baron Strucker observes the 'miracles'—Wanda and Pietro Maximoff—wielding powers derived from Loki's scepter.",
            boxOffice: "$714.4 Million",
            rating: "7.8/10",
            trivia: "Praised as a 1970s political techno-thriller; featured Robert Redford in a deliberate nod to 'All the President's Men'.",
            tags: ["Captain America", "Winter Soldier", "HYDRA", "SHIELD", "Phase 2", "Bucky Barnes", "Falcon"]
        },
        {
            id: "guardians-of-the-galaxy-1",
            title: "Guardians of the Galaxy",
            type: "movie",
            phase: "Phase 2",
            saga: "The Infinity Saga",
            releaseYear: 2014,
            chronologicalOrder: 10,
            chronologicalYear: "2014",
            duration: "121 min",
            director: "James Gunn",
            synopsis: "Brash space adventurer Peter Quill steals a mysterious Orb containing the Power Stone. Pursued by Ronan the Accuser and Thanos, Quill forms an uneasy alliance with four disparate misfits: Gamora, Drax, Rocket, and Groot.",
            comicInspiration: "Dan Abnett and Andy Lanning's (DnA) 2008 relaunch of 'Guardians of the Galaxy'.",
            mainVillain: "Ronan the Accuser (backed by Thanos)",
            keyCharacters: ["Peter Quill / Star-Lord", "Gamora", "Drax the Destroyer", "Rocket Raccoon", "Groot", "Ronan", "Yondu Udonta"],
            postCredits: "The Collector sits in his ruined museum drinking with Howard the Duck.",
            boxOffice: "$773.3 Million",
            rating: "8.0/10",
            trivia: "The soundtrack 'Awesome Mix Vol. 1' topped the Billboard 200 chart—the first soundtrack of previously released songs to do so.",
            tags: ["Guardians of the Galaxy", "Star-Lord", "Power Stone", "Cosmic", "Thanos", "Phase 2"]
        },
        {
            id: "avengers-age-of-ultron",
            title: "Avengers: Age of Ultron",
            type: "movie",
            phase: "Phase 2",
            saga: "The Infinity Saga",
            releaseYear: 2015,
            chronologicalOrder: 11,
            chronologicalYear: "2015",
            duration: "141 min",
            director: "Joss Whedon",
            synopsis: "Tony Stark jumpstarts a dormant peacekeeping program using the Mind Stone, but accidentally creates Ultron: an AI bent on human extinction. The Avengers must assemble to defeat Ultron as he attempts to drop the city of Sokovia like a meteor.",
            comicInspiration: "The Avengers #54-58 (creation of Ultron by Hank Pym in comics) and the 2013 'Age of Ultron' comic storyline.",
            mainVillain: "Ultron (voiced by James Spader)",
            keyCharacters: ["Tony Stark", "Steve Rogers", "Thor", "Bruce Banner", "Natasha Romanoff", "Clint Barton", "Ultron", "Wanda Maximoff", "Pietro Maximoff", "Vision"],
            postCredits: "Thanos retrieves the Infinity Gauntlet, proclaiming: 'Fine, I'll do it myself.'",
            boxOffice: "$1.405 Billion",
            rating: "7.3/10",
            trivia: "Introduced Vision (wielding the Mind Stone) and Scarlet Witch, who would become foundational to the Multiverse Saga.",
            tags: ["Avengers", "Ultron", "Vision", "Scarlet Witch", "Mind Stone", "Sokovia", "Phase 2"]
        },
        {
            id: "captain-america-civil-war",
            title: "Captain America: Civil War",
            type: "movie",
            phase: "Phase 3",
            saga: "The Infinity Saga",
            releaseYear: 2016,
            chronologicalOrder: 13,
            chronologicalYear: "2016",
            duration: "147 min",
            director: "Anthony and Joe Russo",
            synopsis: "Collateral damage leads the United Nations to pass the Sokovia Accords to oversee superheroes. Tony Stark supports government oversight, while Steve Rogers believes in personal accountability. Helmut Zemo exploits their rift using the truth behind Tony Stark's parents' death.",
            comicInspiration: "Mark Millar and Steve McNiven's epic 2006 'Civil War' comic event.",
            mainVillain: "Helmut Zemo",
            keyCharacters: ["Steve Rogers", "Tony Stark", "Bucky Barnes", "T'Challa / Black Panther", "Peter Parker / Spider-Man", "Natasha Romanoff", "Sam Wilson", "Wanda Maximoff", "Vision", "Helmut Zemo"],
            postCredits: "T'Challa grants asylum to Steve and Bucky in Wakanda; Peter Parker explores his new Stark-tech web-shooters displaying a Spider-Signal.",
            boxOffice: "$1.153 Billion",
            rating: "7.8/10",
            trivia: "Marked Tom Holland's debut as Spider-Man and Chadwick Boseman's debut as Black Panther.",
            tags: ["Civil War", "Sokovia Accords", "Iron Man vs Captain America", "Spider-Man", "Black Panther", "Zemo", "Phase 3"]
        },
        {
            id: "doctor-strange-1",
            title: "Doctor Strange",
            type: "movie",
            phase: "Phase 3",
            saga: "The Infinity Saga",
            releaseYear: 2016,
            chronologicalOrder: 14,
            chronologicalYear: "2016 - 2017",
            duration: "115 min",
            director: "Scott Derrickson",
            synopsis: "Arrogant neurosurgeon Stephen Strange loses the use of his hands in a car accident. Seeking healing in Kamar-Taj, he learns mystic arts under the Ancient One, discovering dimensions beyond reality and safeguarding the Time Stone inside the Eye of Agamotto.",
            comicInspiration: "Strange Tales #110 (1963) and Brian K. Vaughan & Marcos Martin's 'Doctor Strange: The Oath' (2006).",
            mainVillain: "Kaecilius & Dormammu of the Dark Dimension",
            keyCharacters: ["Dr. Stephen Strange", "The Ancient One", "Karl Mordo", "Wong", "Christine Palmer", "Kaecilius", "Dormammu"],
            postCredits: "Strange agrees to help Thor locate Odin; Mordo steals Pangborn's magic, declaring 'there are too many sorcerers.'",
            boxOffice: "$677.7 Million",
            rating: "7.5/10",
            trivia: "Benedict Cumberbatch performed both Stephen Strange and the facial mocap/voice for the cosmic entity Dormammu.",
            tags: ["Doctor Strange", "Time Stone", "Eye of Agamotto", "Mystic Arts", "Dormammu", "Phase 3"]
        },
        {
            id: "thor-ragnarok",
            title: "Thor: Ragnarok",
            type: "movie",
            phase: "Phase 3",
            saga: "The Infinity Saga",
            releaseYear: 2017,
            chronologicalOrder: 17,
            chronologicalYear: "2017",
            duration: "130 min",
            director: "Taika Waititi",
            synopsis: "Imprisoned on the trash planet Sakaar without Mjolnir, Thor must survive a gladiatorial contest against his friend the Hulk. He must race back to Asgard to halt Ragnarök—the destruction of his realm—at the hands of his ruthless sister Hela.",
            comicInspiration: "Walt Simonson's classic Thor run (1983-1987) combined with Greg Pak's 'Planet Hulk' (2006).",
            mainVillain: "Hela, the Goddess of Death",
            keyCharacters: ["Thor", "Loki", "Bruce Banner / Hulk", "Valkyrie", "Hela", "Grandmaster", "Korg", "Odin"],
            postCredits: "Thanos's colossal warship, the Sanctuary II, looms over the Asgardian refugee vessel.",
            boxOffice: "$855.3 Million",
            rating: "7.9/10",
            trivia: "Reinvented Thor with Waititi's vibrant color palette and comedic tone; 80% of the film's dialogue was improvised.",
            tags: ["Thor", "Hulk", "Planet Hulk", "Hela", "Asgard", "Ragnarok", "Phase 3"]
        },
        {
            id: "black-panther-1",
            title: "Black Panther",
            type: "movie",
            phase: "Phase 3",
            saga: "The Infinity Saga",
            releaseYear: 2018,
            chronologicalOrder: 15,
            chronologicalYear: "2016",
            duration: "134 min",
            director: "Ryan Coogler",
            synopsis: "Following the death of King T'Chaka, T'Challa returns to the secretive, technologically advanced nation of Wakanda to take the throne. His sovereignty is challenged by Erik Killmonger, an American black-ops operative with royal blood and a desire for global retribution.",
            comicInspiration: "Christopher Priest's definitive Black Panther run (1998) and Ta-Nehisi Coates's 'A Nation Under Our Feet' (2016).",
            mainVillain: "Erik Killmonger (N'Jadaka)",
            keyCharacters: ["T'Challa / Black Panther", "Erik Killmonger", "Nakia", "Okoye", "Shuri", "M'Baku", "Ramonda", "Everett Ross"],
            postCredits: "T'Challa announces at the United Nations that Wakanda will open its borders and share its technology with the world.",
            boxOffice: "$1.349 Billion",
            rating: "7.3/10",
            trivia: "First superhero film nominated for Best Picture at the Academy Awards; won three Oscars (Costume Design, Production Design, Original Score).",
            tags: ["Black Panther", "Wakanda", "Killmonger", "Vibranium", "T'Challa", "Phase 3"]
        },
        {
            id: "avengers-infinity-war",
            title: "Avengers: Infinity War",
            type: "movie",
            phase: "Phase 3",
            saga: "The Infinity Saga",
            releaseYear: 2018,
            chronologicalOrder: 18,
            chronologicalYear: "2018",
            duration: "149 min",
            director: "Anthony and Joe Russo",
            synopsis: "The Mad Titan Thanos embarks on a relentless conquest to harvest all six Infinity Stones. The Avengers, the Guardians of the Galaxy, and the armies of Wakanda unite across Earth and the cosmos to stop him from wiping out half of all life in the universe.",
            comicInspiration: "Jim Starlin's legendary 'The Infinity Gauntlet' (1991) and Jonathan Hickman's 'Infinity' (2013).",
            mainVillain: "Thanos & The Black Order",
            keyCharacters: ["Thanos", "Tony Stark", "Steve Rogers", "Thor", "Bruce Banner", "Doctor Strange", "Peter Parker", "Gamora", "Wanda Maximoff", "Vision", "T'Challa"],
            postCredits: "Nick Fury pages Captain Marvel just as he disintegrates into dust during the Blip.",
            boxOffice: "$2.052 Billion",
            rating: "8.4/10",
            trivia: "Features over 60 established Marvel characters; ends with the villain achieving his goal and wiping out 50% of the universe.",
            tags: ["Infinity War", "Thanos", "The Snap", "Infinity Gauntlet", "Infinity Stones", "Phase 3"]
        },
        {
            id: "avengers-endgame",
            title: "Avengers: Endgame",
            type: "movie",
            phase: "Phase 3",
            saga: "The Infinity Saga",
            releaseYear: 2019,
            chronologicalOrder: 22,
            chronologicalYear: "2018 - 2023",
            duration: "181 min",
            director: "Anthony and Joe Russo",
            synopsis: "Five years after the devastating Blip, the remaining Avengers discover a quantum 'time heist' solution. Journeying through their past to collect the Infinity Stones before Thanos destroyed them, they risk everything to resurrect the fallen and restore the universe.",
            comicInspiration: "The Infinity Gauntlet conclusion, with time-travel elements inspired by 'Avengers Forever' by Kurt Busiek.",
            mainVillain: "Thanos (2014 alternate timeline variant)",
            keyCharacters: ["Tony Stark / Iron Man", "Steve Rogers / Captain America", "Thor", "Bruce Banner / Smart Hulk", "Natasha Romanoff", "Clint Barton / Ronin", "Scott Lang / Ant-Man", "Nebula", "Rocket", "Thanos"],
            postCredits: "No traditional visual scene; audio of Tony Stark hammering his original Mark I armor in the cave echoes over the Marvel logo.",
            boxOffice: "$2.799 Billion",
            rating: "8.4/10",
            trivia: "Briefly became the highest-grossing film of all time in cinema history; culminated 22 interconnected films.",
            tags: ["Endgame", "Avengers", "Time Heist", "I Am Iron Man", "Avengers Assemble", "Infinity Stones", "Phase 3"]
        },
        {
            id: "spider-man-no-way-home",
            title: "Spider-Man: No Way Home",
            type: "movie",
            phase: "Phase 4",
            saga: "The Multiverse Saga",
            releaseYear: 2021,
            chronologicalOrder: 27,
            chronologicalYear: "2024",
            duration: "148 min",
            director: "Jon Watts",
            synopsis: "With Spider-Man's secret identity exposed by Mysterio, Peter asks Doctor Strange to cast a memory-wipe spell. When the spell goes awry, the multiverse ruptures, drawing in supervillains—and alternate Spider-Men—from across cinema history.",
            comicInspiration: "J. Michael Straczynski and Joe Quesada's 'One More Day' (2007) and the 'Spider-Verse' concept.",
            mainVillain: "Norman Osborn / Green Goblin (Willem Dafoe)",
            keyCharacters: ["Peter Parker (Tom Holland)", "Peter Parker (Tobey Maguire)", "Peter Parker (Andrew Garfield)", "Doctor Strange", "MJ", "Ned Leeds", "Green Goblin", "Doc Ock", "Electro", "Aunt May"],
            postCredits: "Eddie Brock & Venom leave a speck of symbiote behind in the MCU universe before being zapped back to their reality.",
            boxOffice: "$1.922 Billion",
            rating: "8.2/10",
            trivia: "United three generations of live-action Spider-Men (Tobey Maguire, Andrew Garfield, and Tom Holland) on screen for the first time.",
            tags: ["Spider-Man", "No Way Home", "Multiverse", "Green Goblin", "Doc Ock", "Doctor Strange", "Phase 4"]
        },
        {
            id: "doctor-strange-multiverse-madness",
            title: "Doctor Strange in the Multiverse of Madness",
            type: "movie",
            phase: "Phase 4",
            saga: "The Multiverse Saga",
            releaseYear: 2022,
            chronologicalOrder: 28,
            chronologicalYear: "2024",
            duration: "126 min",
            director: "Sam Raimi",
            synopsis: "Doctor Strange protects America Chavez, a teenager with the unique ability to punch portals between universes, from the corrupted Scarlet Witch (Wanda Maximoff), who uses the dark magic of the Darkhold to reunite with her children.",
            comicInspiration: "House of M, The Darkhold, and the Illuminati from New Avengers (2005).",
            mainVillain: "Wanda Maximoff / The Scarlet Witch",
            keyCharacters: ["Doctor Strange", "Wanda Maximoff", "America Chavez", "Wong", "Professor Charles Xavier", "Reed Richards (Mister Fantastic)", "Captain Carter", "Black Bolt", "Captain Marvel (Maria Rambeau)"],
            postCredits: "Clea (Charlize Theron) confronts Strange about an incursion he caused, and together they jump into the Dark Dimension.",
            boxOffice: "$955.8 Million",
            rating: "6.9/10",
            trivia: "Featured the live-action debut of Earth-838's Illuminati, including John Krasinski as Reed Richards and Patrick Stewart as Professor X.",
            tags: ["Doctor Strange", "Scarlet Witch", "Multiverse of Madness", "Illuminati", "Darkhold", "Incursions", "Phase 4"]
        },
        {
            id: "deadpool-and-wolverine",
            title: "Deadpool & Wolverine",
            type: "movie",
            phase: "Phase 5",
            saga: "The Multiverse Saga",
            releaseYear: 2024,
            chronologicalOrder: 34,
            chronologicalYear: "2024",
            duration: "128 min",
            director: "Shawn Levy",
            synopsis: "Six years after Deadpool 2, Wade Wilson is plucked from his quiet life by the Time Variance Authority (TVA). Facing the extinction of his universe due to the death of its anchor being (Logan), Wade scours the multiverse to team up with a depressed Wolverine variant and conquer The Void.",
            comicInspiration: "Deadpool Kills the Marvel Universe, Old Man Logan, and the Void from Marvel's comics / Loki series.",
            mainVillain: "Cassandra Nova & Mr. Paradox",
            keyCharacters: ["Wade Wilson / Deadpool", "Logan / Wolverine", "Cassandra Nova", "Mr. Paradox", "Blade (Wesley Snipes)", "Elektra", "Gambit (Channing Tatum)", "Laura / X-23"],
            postCredits: "Deadpool proves to the audience that Johnny Storm (Chris Evans) really did utter the profane remarks about Cassandra Nova.",
            boxOffice: "$1.338 Billion",
            rating: "7.8/10",
            trivia: "Highest-grossing R-rated movie of all time. Brought 20th Century Fox Marvel legacy characters into the MCU.",
            tags: ["Deadpool", "Wolverine", "TVA", "Multiverse", "Mutants", "The Void", "Phase 5"]
        },
        {
            id: "loki-series",
            title: "Loki (Season 1 & 2)",
            type: "series",
            phase: "Phase 4 / 5",
            saga: "The Multiverse Saga",
            releaseYear: 2021,
            chronologicalOrder: 23,
            chronologicalYear: "Outside of Time",
            duration: "12 episodes",
            director: "Kate Herron & Justin Benson / Aaron Moorhead",
            synopsis: "After escaping with the Tesseract in Endgame, the 2012 variant of Loki is apprehended by the Time Variance Authority (TVA). Working with Agent Mobius and female variant Sylvie, Loki uncovers the secret architect of the Sacred Timeline: He Who Remains. In Season 2, Loki sacrifices his freedom to become the God of Stories, weaving time together at the heart of the multiverse.",
            comicInspiration: "Al Ewing's 'Loki: Agent of Asgard' (2014) and Mark Gruenwald's TVA lore.",
            mainVillain: "He Who Remains / Kang variants & Victor Timely",
            keyCharacters: ["Loki / God of Stories", "Sylvie", "Mobius M. Mobius", "He Who Remains", "Ravonna Renslayer", "Hunter B-15", "Ouroboros (O.B.)"],
            postCredits: "Setup for the Kang dynasty and the emergence of the multiversal war.",
            boxOffice: "Disney+ Original",
            rating: "8.2/10",
            trivia: "Loki's transformation into the God of Stories anchors the entire MCU multiverse tree structure (Yggdrasil).",
            tags: ["Loki", "TVA", "Multiverse", "Kang", "He Who Remains", "God of Stories", "Sacred Timeline"]
        }
    ],

    storylines: [
        {
            id: "secret-wars-2015",
            title: "Secret Wars (2015)",
            year: 2015,
            writer: "Jonathan Hickman",
            artist: "Esad Ribić",
            universe: "Multiverse / Battleworld",
            prelude: "The Multiversal Incursions: parallel Earths colliding and obliterating both universes. The Illuminati (Iron Man, Reed Richards, Namor, Black Panther, Beast) secretly destroyed alternate worlds to buy time, while the Beyonders systematically slaughtered the Living Tribunal and the Celestials.",
            synopsis: "The final incursion between Earth-616 (Main Marvel) and Earth-1610 (Ultimate Marvel) destroys the multiverse. Doctor Doom, using the absorbed power of the Beyonders channeled through Molecule Man, rescues fragments of dead realities and stitches them into a singular patchwork planet: 'Battleworld'. Doom reigns supreme as 'God Emperor Doom' with Doctor Strange as his Sheriff. Surviving heroes and villains from life-rafts awaken to challenge Doom's omnipotence.",
            coreIssues: "Secret Wars #1-9 (2015), preceded by Hickman's 'New Avengers' Vol. 3 #1-33 and 'Avengers' Vol. 5 #1-44.",
            readingOrder: [
                "Avengers (Vol. 5) #1-44 & New Avengers (Vol. 3) #1-33 (The Incursions)",
                "Secret Wars #0 (FCBD 2015)",
                "Secret Wars #1 (The Final Incursion - Earth-616 vs Earth-1610)",
                "Secret Wars #2-4 (God Emperor Doom & The Life Rafts Open)",
                "Secret Wars #5-7 (Doom's Court & The Rebellion)",
                "Secret Wars #8-9 (Reed Richards vs Doctor Doom: The Rebirth of the Multiverse)"
            ],
            consequences: "Doctor Doom admits Reed Richards would have ruled better; Molecule Man transfers the divine power to Reed Richards. The Fantastic Four rebuild the Marvel Multiverse. Miles Morales and his family are integrated into the main Earth-616 continuity.",
            mcuAdaptation: "Slated to be adapted as the epic culmination of MCU Phase 6: 'Avengers: Secret Wars' (directed by the Russo Brothers, starring Robert Downey Jr. as Doctor Doom).",
            keyCharacters: ["Doctor Doom (God Emperor)", "Reed Richards (Mister Fantastic)", "Molecule Man", "Doctor Strange", "Black Panther", "Namor", "Miles Morales", "The Beyonders", "Thanos"],
            tags: ["Secret Wars", "Doctor Doom", "Battleworld", "Incursions", "Multiverse", "Fantastic Four", "Hickman"]
        },
        {
            id: "the-infinity-gauntlet-1991",
            title: "The Infinity Gauntlet",
            year: 1991,
            writer: "Jim Starlin",
            artist: "George Pérez and Ron Lim",
            universe: "Earth-616",
            prelude: "Resurrected by Mistress Death to eliminate half the population of the universe to restore balance, Thanos outwits the Elders of the Universe (Grandmaster, Collector, Runner, Champion, Gardener, and In-Betweener) in 'Thanos Quest' #1-2 to claim all six Soul Gems (Infinity Gems).",
            synopsis: "With all six Infinity Gems embedded in his golden gauntlet, Thanos possesses omnipotence, omnipresence, and omniscience. To win the affection of Mistress Death, who still spurns him, Thanos snaps his fingers, instantly eradicating half of all sentient life across creation. Earth's remaining superheroes, guided by the resurrected cosmic messiah Adam Warlock and Doctor Strange, mount a desperate assault, followed by cosmic entities including Galactus, Eternity, and the Living Tribunal.",
            coreIssues: "The Infinity Gauntlet #1-6 (1991), preceded by 'Thanos Quest' #1-2 and 'Silver Surfer' #34-50.",
            readingOrder: [
                "Silver Surfer (Vol. 3) #34-38 (Return of Thanos)",
                "Thanos Quest #1-2 (Thanos gathers the six gems)",
                "The Infinity Gauntlet #1 (The Snap happens)",
                "The Infinity Gauntlet #2-3 (Earth's heroes mobilize under Adam Warlock)",
                "The Infinity Gauntlet #4 (Thanos slaughters the heroes)",
                "The Infinity Gauntlet #5 (Cosmic pantheon attacks; Nebula seizes the Gauntlet)",
                "The Infinity Gauntlet #6 (Adam Warlock claims the Gauntlet; Thanos becomes a farmer)"
            ],
            consequences: "The Living Tribunal decrees the Infinity Gems can never again be used in unison. Adam Warlock forms the 'Infinity Watch', entrusting individual gems to Gamora, Pip the Troll, Drax, Moondragon, and secretly Thanos.",
            mcuAdaptation: "Heavily adapted in MCU's 'Avengers: Infinity War' and 'Avengers: Endgame', though the MCU replaced Thanos's romantic infatuation with Death with an ecological/resource ideology.",
            keyCharacters: ["Thanos", "Adam Warlock", "Silver Surfer", "Mistress Death", "Doctor Strange", "Captain America", "Nebula", "Galactus", "Eternity"],
            tags: ["Infinity Gauntlet", "Thanos", "The Snap", "Adam Warlock", "Silver Surfer", "Infinity Stones", "Starlin"]
        },
        {
            id: "civil-war-2006",
            title: "Civil War",
            year: 2006,
            writer: "Mark Millar",
            artist: "Steve McNiven",
            universe: "Earth-616",
            prelude: "The New Warriors, a reckless young superhero team filming a reality TV show, botch an ambush on supervillain Nitro in Stamford, Connecticut. Nitro self-detonates near an elementary school, killing over 600 civilians, including 60 children.",
            synopsis: "Public outrage forces the U.S. government to enact the Superhuman Registration Act (SHRA), requiring all masked vigilantes to unmask, register their real identities, and undergo government training. Tony Stark, Hank Pym, and Reed Richards champion the law. Captain America (Steve Rogers) refuses, declaring it a violation of civil liberties, and goes underground leading the 'Secret Avengers'. Superheroes clash violently, family ties dissolve, and Peter Parker unmasks on live international television before defecting.",
            coreIssues: "Civil War #1-7 (2006), Amazing Spider-Man #532-538, Captain America #22-25.",
            readingOrder: [
                "Civil War Opening Shot / Illuminati #1",
                "Civil War #1 (Stamford Tragedy & The Act enacted)",
                "Amazing Spider-Man #532-533 (Peter Parker reveals identity)",
                "Civil War #2-3 (Cap goes underground; Iron Man creates cloned Thor 'Ragnarok')",
                "Civil War #4 (Goliath is murdered by Thor clone; Spidey defects)",
                "Civil War #5-6 (The Punisher joins; Negative Zone prison 42 infiltrated)",
                "Civil War #7 (Climactic battle in Times Square; Cap surrenders to protect civilians)"
            ],
            consequences: "Tony Stark is appointed Director of S.H.I.E.L.D. and institutes the Fifty-State Initiative. Steve Rogers is assassinated on the courthouse steps ('The Death of Captain America'). Peter Parker is driven into hiding, leading to 'Back in Black' and 'One More Day'.",
            mcuAdaptation: "Adapted in 'Captain America: Civil War' (2016), scaled down from thousands of heroes to an ideological confrontation between Steve Rogers and Tony Stark over the Sokovia Accords.",
            keyCharacters: ["Captain America (Steve Rogers)", "Iron Man (Tony Stark)", "Spider-Man (Peter Parker)", "Mister Fantastic (Reed Richards)", "Goliath (Bill Foster)", "Bucky Barnes", "Luke Cage"],
            tags: ["Civil War", "Superhuman Registration Act", "Iron Man", "Captain America", "Stamford", "Secret Avengers"]
        },
        {
            id: "house-of-m-2005",
            title: "House of M",
            year: 2005,
            writer: "Brian Michael Bendis",
            artist: "Olivier Coipel",
            universe: "Earth-58163 / Earth-616",
            prelude: "Following the mental collapse of Wanda Maximoff in 'Avengers Disassembled' (which resulted in the deaths of Hawkeye, Vision, and Ant-Man Scott Lang), Professor X and Magneto struggle to stabilize her reality-warping powers in Genosha.",
            synopsis: "As the Avengers and X-Men debate whether Wanda must be killed for the safety of humanity, Quicksilver convinces Wanda to reshape reality into a paradise where mutants are the dominant ruling class and humans are the oppressed minority—with their father, Magneto, reigning over the 'House of M'. Only Wolverine awakens with full memories of the original timeline and rallies the heroes. When Magneto realizes Quicksilver manipulated Wanda, he kills him. An enraged, grief-stricken Wanda utters three devastating words: 'No More Mutants.'",
            coreIssues: "House of M #1-8 (2005), plus tie-ins in New X-Men, Spider-Man: House of M.",
            readingOrder: [
                "Avengers Disassembled (Prelude)",
                "House of M #1-2 (The World is rewritten)",
                "House of M #3-4 (Wolverine recalls the truth; Layla Miller awakens heroes)",
                "House of M #5-6 (The assault on Genosha palace)",
                "House of M #7 (Magneto strikes Quicksilver; Wanda snaps)",
                "House of M #8 ('No More Mutants' & M-Day Decimation)"
            ],
            consequences: "M-Day: 98% of the mutant population instantly loses their X-gene, reducing mutantkind from millions to approximately 198 individuals and triggering an existential extinction crisis for mutantkind for the next decade.",
            mcuAdaptation: "Loosely inspired the sitcom reality-warping anomaly in Disney+'s 'WandaVision' and Wanda's emotional grief in 'Doctor Strange in the Multiverse of Madness'.",
            keyCharacters: ["Scarlet Witch (Wanda Maximoff)", "Magneto", "Quicksilver (Pietro Maximoff)", "Wolverine", "Professor X", "Layla Miller", "Emma Frost", "Spider-Man"],
            tags: ["House of M", "Scarlet Witch", "No More Mutants", "Magneto", "M-Day", "Mutants", "X-Men", "Bendis"]
        },
        {
            id: "age-of-apocalypse-1995",
            title: "Age of Apocalypse",
            year: 1995,
            writer: "Scott Lobdell, Fabian Nicieza, Mark Waid",
            artist: "Joe Madureira, Andy Kubert, Steve Epting",
            universe: "Earth-295",
            prelude: "Legion (David Haller), the mentally unstable mutant son of Charles Xavier, travels back in time to murder Magneto before he can oppose Xavier's dream of peace. However, young Xavier jumps in front of the psionic blast and dies instead.",
            synopsis: "Without Charles Xavier to guide mutantkind, En Sabah Nur (Apocalypse) awakens a decade early and conquers North America, enforcing Darwinian rule: 'Survival of the Fittest.' Magneto, inspired by his fallen friend's dream, forms and leads the X-Men in an apocalyptic guerrilla war against Apocalypse and his Four Horsemen. The lone survivor who remembers the original universe, Bishop, must navigate a dystopian nightmare to reverse history.",
            coreIssues: "X-Men Alpha, Generation Next, Astonishing X-Men, Weapon X, Factor X, Gambit & the X-Ternals, Amazing X-Men, X-Calibre, X-Men Omega.",
            readingOrder: [
                "Legion Quest (Prelude)",
                "X-Men Alpha (The World of AoA introduced)",
                "Astonishing X-Men & Weapon X Vol. 1",
                "Factor X & Amazing X-Men",
                "X-Men: Prime / X-Men Omega (Final Assault and Timeline Restoration)"
            ],
            consequences: "One of the most acclaimed alternative-reality epics in comic history; introduced fan-favorite characters like Nate Grey (X-Man), Dark Beast, and Blink to the main Marvel Universe.",
            mcuAdaptation: "Elements influenced 'X-Men: Apocalypse' (2016) and various alternate timelines in animated series.",
            keyCharacters: ["Apocalypse (En Sabah Nur)", "Magneto (Leader of X-Men)", "Bishop", "Weapon X (Logan with one hand)", "Nate Grey (X-Man)", "Dark Beast", "Cyclops", "Jean Grey"],
            tags: ["Age of Apocalypse", "Apocalypse", "X-Men", "Earth-295", "Magneto", "Bishop", "Time Travel"]
        },
        {
            id: "spider-verse-2014",
            title: "Spider-Verse",
            year: 2014,
            writer: "Dan Slott",
            artist: "Olivier Coipel and Giuseppe Camuncoli",
            universe: "Web of Life and Destiny / Multiverse",
            prelude: "The Inheritors, a clan of vampiric immortal predators led by Morlun and Lord Solus, hunt and consume 'Spider-Totems' across every reality in the multiverse to sustain their immortality.",
            synopsis: "Facing genocide, every Spider-Man, Spider-Woman, and Spider-Being across infinite dimensions must unite into a grand Spider-Army. Led by Earth-616 Peter Parker (the greatest totem) and Superior Spider-Man (Doc Ock's mind in Peter's body), the Spiders wage a cross-dimensional war to protect the 'Scion' (Benjy Parker), the 'Bride' (Silk), and the 'Other' (Kaine) from the Inheritors.",
            coreIssues: "Amazing Spider-Man (Vol. 3) #7-14, Superior Spider-Man #32-33, Edge of Spider-Verse #1-5.",
            readingOrder: [
                "Edge of Spider-Verse #1-5 (Debut of Spider-Gwen / Gwen Stacy of Earth-65)",
                "Superior Spider-Man #32-33",
                "Amazing Spider-Man (Vol. 3) #9-11 (The Gathering of the Web)",
                "Spider-Verse Team-Up #1-3 & Scarlet Spiders #1-3",
                "Amazing Spider-Man (Vol. 3) #12-14 (Climactic battle on Loomworld)"
            ],
            consequences: "Spider-Gwen became a global cultural sensation; cemented the Multiverse concept for Spider-Man; inspired Sony's Oscar-winning animated films.",
            mcuAdaptation: "Directly inspired Sony's animated masterpieces 'Spider-Man: Into the Spider-Verse' and 'Across the Spider-Verse', and influenced 'Spider-Man: No Way Home'.",
            keyCharacters: ["Peter Parker (Earth-616)", "Superior Spider-Man (Otto Octavius)", "Spider-Gwen (Gwen Stacy)", "Miles Morales", "Spider-Man 2099 (Miguel O'Hara)", "Spider-Ham", "Morlun", "Silk (Cindy Moon)"],
            tags: ["Spider-Verse", "Spider-Man", "Spider-Gwen", "Miles Morales", "Spider-Man 2099", "Morlun", "Multiverse"]
        },
        {
            id: "planet-hulk-and-world-war-hulk",
            title: "Planet Hulk & World War Hulk",
            year: 2006,
            writer: "Greg Pak",
            artist: "Carlo Pagulayan, Aaron Lopresti, John Romita Jr.",
            universe: "Earth-616 / Sakaar",
            prelude: "Deeming the Hulk too dangerous for Earth after he devastates Las Vegas, the Illuminati (Tony Stark, Reed Richards, Doctor Strange, Black Bolt) deceive the Hulk into an orbital satellite and launch him toward an uninhabited peaceful paradise world.",
            synopsis: "The shuttle drifts through a wormhole, crash-landing on the brutal gladiatorial planet Sakaar. Enslaved with an obedience disk, Hulk rises through the Great Arena, earns the moniker 'Green Scar', overthrows the tyrannical Red King, and is crowned emperor alongside Queen Caiera. When the Illuminati shuttle's warp engine detonates, incinerating millions—including his pregnant wife Caiera—an enraged World-Breaker Hulk returns to Earth accompanied by his Warbound alien army with one objective: vengeance against the heroes who exiled him.",
            coreIssues: "Incredible Hulk #92-105 (Planet Hulk), World War Hulk #1-5 (2007).",
            readingOrder: [
                "Incredible Hulk (Vol. 2) #88-91 (Illuminati Exile)",
                "Planet Hulk: Exile & Anarchy (Incredible Hulk #92-100)",
                "Planet Hulk: Armageddon (Incredible Hulk #101-105)",
                "World War Hulk #1 (Hulk demands Iron Man, Strange, Reed, and Black Bolt surrender)",
                "World War Hulk #2-3 (Hulk crushes Iron Man Hulkbuster, Fantastic Four & Ghost Rider)",
                "World War Hulk #4 (Doctor Strange merges with Zom; Hulk enslaves heroes in Madison Square Garden arena)",
                "World War Hulk #5 (The Sentry clashes with Hulk; treachery of Miek exposed)"
            ],
            consequences: "Exposed the moral compromises of the Illuminati; birthed Skaar, Son of Hulk; set the stage for the creation of the Red Hulk (General Ross).",
            mcuAdaptation: "Elements of Planet Hulk's Sakaar gladiatorial arena, Korg, and Miek were adapted in 'Thor: Ragnarok' (2017).",
            keyCharacters: ["Hulk / Green Scar / World-Breaker", "Caiera the Oldstrong", "The Illuminati", "The Sentry", "Miek", "Korg", "Hiroim", "Red King"],
            tags: ["Planet Hulk", "World War Hulk", "Hulk", "Illuminati", "Sakaar", "Sentry", "Green Scar"]
        },
        {
            id: "the-dark-phoenix-saga-1980",
            title: "The Dark Phoenix Saga",
            year: 1980,
            writer: "Chris Claremont",
            artist: "John Byrne",
            universe: "Earth-616",
            prelude: "Jean Grey saves the X-Men by piloting a damaged space shuttle through a lethal solar radiation storm, merging with the primal cosmic entity known as the Phoenix Force.",
            synopsis: "Manipulated and mentally seduced by Mastermind and the Hellfire Club into becoming their 'Black Queen', Jean Grey loses psychological control of the cosmic entity within her. Reborn as the all-consuming 'Dark Phoenix', she flies across the cosmos and consumes the D'Bari star system, wiping out five billion innocent extraterrestrial beings. The Shi'ar Empire, led by Empress Lilandra, puts Jean on trial for universal genocide, culminating in a tragic duel on the Blue Area of the Moon.",
            coreIssues: "The X-Men #129-138 (1980).",
            readingOrder: [
                "Uncanny X-Men #129-131 (Debut of Kitty Pryde, Dazzler & Hellfire Club)",
                "Uncanny X-Men #132-134 (The Black Queen & Mental Corruption)",
                "Uncanny X-Men #135 (Birth of Dark Phoenix & D'Bari star devoured)",
                "Uncanny X-Men #136 (Return to Earth & Xavier's psychic cage)",
                "Uncanny X-Men #137 (Trial by Combat on the Moon & Jean's ultimate sacrifice)"
            ],
            consequences: "Considered by many the single greatest comic book storyline in Marvel history. Cemented Jean Grey's tragic mythos and established the cosmic hierarchy of the Phoenix Force.",
            mcuAdaptation: "Adapted twice by 20th Century Fox ('X-Men: The Last Stand' in 2006 and 'Dark Phoenix' in 2019).",
            keyCharacters: ["Jean Grey / Dark Phoenix", "Cyclops (Scott Summers)", "Wolverine (Logan)", "Professor X (Charles Xavier)", "Mastermind (Jason Wyngarde)", "Sebastian Shaw", "Empress Lilandra"],
            tags: ["Dark Phoenix", "Jean Grey", "X-Men", "Phoenix Force", "Claremont", "Hellfire Club", "Cyclops"]
        },
        {
            id: "annihilation-2006",
            title: "Annihilation",
            year: 2006,
            writer: "Keith Giffen, Dan Abnett, Andy Lanning",
            artist: "Andrea Di Vito",
            universe: "Earth-616 (Cosmic)",
            prelude: "From the depths of the Negative Zone, the insectoid tyrant Annihilus marshals an apocalyptic swarm of bioships known as the Annihilation Wave.",
            synopsis: "The Annihilation Wave breaches the Crunch and decimates the Nova Corps and the Kyln planetary prison in minutes. With Earth's heroes distracted by Civil War, Richard Rider (Nova Prime), Peter Quill (Star-Lord), Drax the Destroyer, Silver Surfer, and Ronan the Accuser lead the 'United Front' in a desperate galactic war for survival. Annihilus enslaves Galactus to power a star-killing cosmic superweapon.",
            coreIssues: "Annihilation: Prologue, Annihilation: Nova #1-4, Silver Surfer #1-4, Super-Skrull #1-4, Ronan #1-4, Annihilation #1-6.",
            readingOrder: [
                "Annihilation: Prologue #1",
                "Annihilation: Nova #1-4 & Silver Surfer #1-4",
                "Annihilation: Super-Skrull #1-4 & Ronan #1-4",
                "Annihilation #1-3 (United Front stands on Daedalus 5)",
                "Annihilation #4-6 (Drax kills Thanos; Nova Prime executes Annihilus)"
            ],
            consequences: "Rejuvenated Marvel's entire cosmic library; directly birthed the modern 2008 Guardians of the Galaxy team, which later became the blueprint for the MCU blockbuster franchise.",
            mcuAdaptation: "Inspired the destruction of Xandar and the Nova Corps referenced in 'Avengers: Infinity War'.",
            keyCharacters: ["Richard Rider / Nova Prime", "Annihilus", "Thanos", "Drax the Destroyer", "Peter Quill / Star-Lord", "Galactus", "Silver Surfer", "Phyla-Vell"],
            tags: ["Annihilation", "Nova", "Annihilus", "Cosmic", "Guardians of the Galaxy", "Galactus", "Silver Surfer"]
        },
        {
            id: "secret-invasion-2008",
            title: "Secret Invasion",
            year: 2008,
            writer: "Brian Michael Bendis",
            artist: "Leinil Francis Yu",
            universe: "Earth-616",
            prelude: "Following the annihilation of their homeworld by Galactus, the Skrulls, led by Queen Veranke, conclude that Earth is their prophesied new home: 'He loves you.' Utilizing genetic infiltration techniques, Skrulls replace prominent superheroes and politiciansundetected by magic, telepathy, or technology.",
            synopsis: "The revelation that Elektra was a Skrull imposter ignites pervasive paranoia: 'Who do you trust?' A Skrull spaceship lands in the Savage Land containing retro-suited heroes, sowing confusion. Queen Veranke (posing as Spider-Woman) incapacitates S.H.I.E.L.D., Stark Industries, and the Raft prison. The fragmented Avengers, the Thunderbolts, Nick Fury's Secret Warriors, and Norman Osborn's villains join forces in Central Park for a bloody last stand.",
            coreIssues: "Secret Invasion #1-8 (2008), New Avengers #40-47, Mighty Avengers #12-20.",
            readingOrder: [
                "New Avengers: Illuminati #5 (Discovery of Skrull infiltration)",
                "New Avengers #31-39 (Elektra revealed as Skrull)",
                "Secret Invasion #1-3 (Paranoia explodes; Savage Land confrontation)",
                "Secret Invasion #4-6 (Assault on Manhattan; Thor & Cap return)",
                "Secret Invasion #7-8 (Battle of Central Park; Norman Osborn shoots Veranke)"
            ],
            consequences: "Tony Stark is disgraced and stripped of authority. Norman Osborn is hailed as a global hero and given control of S.H.I.E.L.D. (rebranded as H.A.M.M.E.R.), ushering in the 'Dark Reign' era.",
            mcuAdaptation: "Adapted as the 2023 Disney+ series 'Secret Invasion' starring Samuel L. Jackson and Emilia Clarke, though with a radically different espionage tone.",
            keyCharacters: ["Queen Veranke", "Iron Man", "Captain America", "Thor", "Nick Fury", "Norman Osborn", "Spider-Woman", "Hank Pym (Skrull Criti Noll)"],
            tags: ["Secret Invasion", "Skrulls", "Who Do You Trust", "Norman Osborn", "Dark Reign", "Bendis"]
        }
    ],

    characters: [
        {
            id: "iron-man",
            name: "Tony Stark",
            alias: "Iron Man",
            firstAppearance: "Tales of Suspense #39 (March 1963)",
            creators: "Stan Lee, Larry Lieber, Don Heck, Jack Kirby",
            universe: "Earth-616 (Main) & Earth-199999 (MCU)",
            powers: [
                "Genius-level intellect & master engineer",
                "Advanced powered exoskeletons with nanotech (Mark I through Mark 85)",
                "Flight via repulsor boot jets (Mach 10+ capable)",
                "Uni-beam chest projector & repulsor rays",
                "Heuristic AI tactical assistance (J.A.R.V.I.S. & F.R.I.D.A.Y.)"
            ],
            powerGrid: {
                intelligence: 6,
                strength: 6,
                speed: 5,
                durability: 6,
                energyProjection: 6,
                fightingSkills: 4
            },
            comicBio: "Anthony Edward Stark inherited Stark Industries after his parents died. After suffering a shrapnel chest injury in a terrorist ambush, he built the iconic armor to keep his heart beating. He co-founded the Avengers, led the pro-registration side in Civil War, and became Director of S.H.I.E.L.D.",
            mcuBio: "Portrayed by Robert Downey Jr. Kicked off the MCU in 2008. Evolved from a self-absorbed weapons manufacturer into the universe's ultimate savior, sacrificing his life in 'Avengers: Endgame' by wielding the Infinity Stones to snap Thanos and his army out of existence.",
            comicVsMcuDiff: "In comics, Stark had a longer, more agonizing battle with alcoholism ('Demon in a Bottle') and was often morally grayer during Civil War, creating a secret Negative Zone prison. In the MCU, his wit and charm redefined the character forever, heavily influencing the comic version back.",
            majorStorylines: ["Demon in a Bottle", "Armor Wars", "Extremis", "Civil War", "Invincible Iron Man: World's Most Wanted"],
            tags: ["Iron Man", "Avengers", "Stark", "MCU", "Infinity Saga"]
        },
        {
            id: "spider-man-peter",
            name: "Peter Parker",
            alias: "Spider-Man",
            firstAppearance: "Amazing Fantasy #15 (August 1962)",
            creators: "Stan Lee, Steve Ditko",
            universe: "Earth-616 (Main) & Earth-199999 (MCU)",
            powers: [
                "Proportional strength, speed, agility, and reflexes of a spider",
                "Ability to cling to almost any solid surface (wall-crawling)",
                "Precognitive 'Spider-Sense' warning of impending danger",
                "Genius scientific intellect; invented synthetic web-fluid and mechanical web-shooters",
                "Accelerated healing factor and high pain tolerance"
            ],
            powerGrid: {
                intelligence: 5,
                strength: 4,
                speed: 4,
                durability: 3,
                energyProjection: 1,
                fightingSkills: 5
            },
            comicBio: "Bitten by a radioactive spider at a science exhibit, high school orphan Peter Parker sought money and fame until his selfish inaction allowed a burglar to murder his beloved Uncle Ben. Learning that 'With great power there must also come great responsibility,' he became Earth's most enduring protector.",
            mcuBio: "Portrayed by Tom Holland. Mentored by Tony Stark during Civil War and Infinity War. In 'No Way Home', after the death of Aunt May, Peter orchestrates a multiversal memory wipe, choosing total anonymity and living in a modest apartment while continuing his solo vigilante crusade.",
            comicVsMcuDiff: "Comic Peter struggled extensively with poverty, employment at the Daily Bugle, marriage to Mary Jane Watson, and was purely independent without Stark providing high-tech nanotech suits until later in Civil War. MCU Peter had early access to Stark tech before stripping it all away.",
            majorStorylines: ["The Night Gwen Stacy Died", "Kraven's Last Hunt", "Spider-Man No More!", "The Alien Costume / Birth of Venom", "Spider-Verse"],
            tags: ["Spider-Man", "Peter Parker", "Web-Slinger", "Street Level", "Avengers", "Responsibility"]
        },
        {
            id: "scarlet-witch",
            name: "Wanda Maximoff",
            alias: "Scarlet Witch",
            firstAppearance: "The X-Men #4 (March 1964)",
            creators: "Stan Lee, Jack Kirby",
            universe: "Earth-616 (Main) & Earth-199999 (MCU)",
            powers: [
                "Chaos Magic manipulation & reality warping",
                "Probability alteration ('Hexes')",
                "Telekinesis, levitation, and energy shields",
                "Telepathy, mind control, and illusion generation",
                "Astral projection and dimensional traversal"
            ],
            powerGrid: {
                intelligence: 3,
                strength: 2,
                speed: 2,
                durability: 2,
                energyProjection: 6,
                fightingSkills: 3
            },
            comicBio: "Originally depicted as a mutant daughter of Magneto (later retconned to genetic experimentation by the High Evolutionary), Wanda's natural aptitude for mystical arts channels primal Chaos Magic granted by Elder God Chthon. In House of M, her grief eradicated 98% of mutantkind.",
            mcuBio: "Portrayed by Elizabeth Olsen. Experimented on with the Mind Stone in Sokovia. In 'WandaVision', her grief over Vision's death created the Westview Hex. Corrupted by the Darkhold in 'Multiverse of Madness', she embarked on a multiversal rampage before sacrificing herself to destroy every copy of the Darkhold.",
            comicVsMcuDiff: "In comics, Wanda has twin sons (Billy and Tommy) created from fragments of Mephisto's soul who later reincarnate as Young Avengers Wiccan and Speed. In the MCU, her powers stem from both an innate witch origin and the Mind Stone.",
            majorStorylines: ["Avengers Disassembled", "House of M", "The Children's Crusade", "Trial of Magneto", "Darkhold Alpha"],
            tags: ["Scarlet Witch", "Chaos Magic", "Wanda", "House of M", "Darkhold", "Mutants"]
        },
        {
            id: "doctor-doom",
            name: "Victor Von Doom",
            alias: "Doctor Doom",
            firstAppearance: "The Fantastic Four #5 (July 1962)",
            creators: "Stan Lee, Jack Kirby",
            universe: "Earth-616 (Main Latveria)",
            powers: [
                "Mastery of both supreme Sorcery and cutting-edge Science",
                "Genius-level intellect rivaling or exceeding Reed Richards",
                "Titanium powered armor granting super strength, force fields, and energy blasts",
                "Diplomatic immunity as sovereign monarch of Latveria",
                "Doombot robotic duplicates indistinguishable from the real Doom"
            ],
            powerGrid: {
                intelligence: 6,
                strength: 4,
                speed: 2,
                durability: 5,
                energyProjection: 6,
                fightingSkills: 4
            },
            comicBio: "Born to Romani parents in Latveria, Victor Von Doom sought to master both arcane magic and cybernetics to rescue his mother's soul from Mephisto. After a college explosion scarred his face, he donned his titanium mask and conquered Latveria. He is the ultimate arch-nemesis of the Fantastic Four, and saved the dying multiverse as 'God Emperor Doom' in Secret Wars 2015.",
            mcuBio: "Announced to debut in the MCU as the premier villain of the Multiverse Saga, portrayed by Robert Downey Jr. in 'Avengers: Doomsday' (2026) and 'Avengers: Secret Wars' (2027).",
            comicVsMcuDiff: "In comics, Doom is driven by a genuine tragic belief that only through his absolute autocratic rule can humanity avoid self-destruction (verified by the Panther God Bast).",
            majorStorylines: ["Secret Wars (1984 & 2015)", "Books of Doom", "Triumph and Torment", "Doomwar", "Infamous Iron Man"],
            tags: ["Doctor Doom", "Latveria", "Fantastic Four", "Secret Wars", "God Emperor Doom", "Villain"]
        },
        {
            id: "thanos",
            name: "Thanos",
            alias: "The Mad Titan",
            firstAppearance: "The Invincible Iron Man #55 (February 1973)",
            creators: "Jim Starlin",
            universe: "Earth-616 (Titan) & Earth-199999 (MCU)",
            powers: [
                "Deviant-Eternal physiology granting colossal strength, stamina, and invulnerability",
                "Cosmic energy projection and manipulation",
                "Superhuman tactical and strategic intellect",
                "Immense mental resilience against telepathic intrusion",
                "Mastery of cosmic artifacts (Infinity Gauntlet, Cosmic Cube)"
            ],
            powerGrid: {
                intelligence: 6,
                strength: 7,
                speed: 3,
                durability: 6,
                energyProjection: 6,
                fightingSkills: 6
            },
            comicBio: "Born on Saturn's moon Titan with the mutated Deviant gene, Thanos became infatuated with the physical embodiment of Mistress Death. To appease her, he committed planet-wide genocides, stole the Infinity Gems, and wiped out half the universe in 1991's 'The Infinity Gauntlet'.",
            mcuBio: "Portrayed by Josh Brolin. Believing overpopulation caused the collapse of his home planet Titan, he sought the six Infinity Stones to erase half of all life at random, viewing his genocide as a merciful, dispassionate balance. Decapitated by Thor in 2018; his 2014 variant was dusted by Tony Stark in 'Endgame'.",
            comicVsMcuDiff: "Comic Thanos is driven by poetic nihilism and romantic obsession with Mistress Death; MCU Thanos is driven by a messianic savior complex regarding universal scarcity.",
            majorStorylines: ["The Thanos Quest", "The Infinity Gauntlet", "Infinity War", "Annihilation", "Infinity (2013)"],
            tags: ["Thanos", "Infinity Gauntlet", "Mad Titan", "The Snap", "Titan", "Cosmic"]
        },
        {
            id: "doctor-strange",
            name: "Dr. Stephen Strange",
            alias: "Doctor Strange",
            firstAppearance: "Strange Tales #110 (July 1963)",
            creators: "Stan Lee, Steve Ditko",
            universe: "Earth-616 & Earth-199999 (MCU)",
            powers: [
                "Mastery of the Mystic Arts (Sorcerer Supreme of Earth)",
                "Dimensional travel, portal creation (Sling Ring), and mirror dimension trapping",
                "Artifacts: Cloak of Levitation, Eye of Agamotto, Book of Vishanti",
                "Astral projection and soul manipulation",
                "Time manipulation (formerly via the Time Stone)"
            ],
            powerGrid: {
                intelligence: 4,
                strength: 2,
                speed: 2,
                durability: 3,
                energyProjection: 6,
                fightingSkills: 4
            },
            comicBio: "Egoistical surgeon Stephen Strange found humility in Tibet after a car crash wrecked his nerves. Studying under the Ancient One, he proved worthy of inheriting the mantle of Sorcerer Supreme, protecting Earth from cosmic horrors like Dormammu, Nightmare, and Shuma-Gorath.",
            mcuBio: "Portrayed by Benedict Cumberbatch. Played the pivotal role in Endgame by seeing 14,000,605 futures and identifying the single winning timeline. Confronted Wanda Maximoff across parallel realities in 'Multiverse of Madness' and incurred multiversal incursions.",
            comicVsMcuDiff: "In comics, Strange was officially Sorcerer Supreme for decades without interruption, frequently using terrifying black magic when cosmic stakes demanded it. In MCU, Wong became Sorcerer Supreme on a technicality during the five-year Blip.",
            majorStorylines: ["The Oath", "Doctor Strange: Master of the Mystic Arts", "A Separate Reality", "Triumph and Torment", "The Death of Doctor Strange"],
            tags: ["Doctor Strange", "Sorcerer Supreme", "Mystic Arts", "Eye of Agamotto", "Multiverse"]
        },
        {
            id: "thor",
            name: "Thor Odinson",
            alias: "God of Thunder",
            firstAppearance: "Journey into Mystery #83 (August 1962)",
            creators: "Stan Lee, Larry Lieber, Jack Kirby",
            universe: "Earth-616 (Asgard) & Earth-199999 (MCU)",
            powers: [
                "Asgardian deity physiology: godlike strength, endurance, and near-immortality",
                "Atmospheric and weather control: lightning, rain, wind, and cosmic storms",
                "Weapon mastery: Mjolnir (enchanted uru hammer) and Stormbreaker",
                "Flight and dimensional teleportation via Mjolnir / Bifrost",
                "Godblast: concentrated blast of divine life essence capable of slaying immortals"
            ],
            powerGrid: {
                intelligence: 2,
                strength: 7,
                speed: 5,
                durability: 6,
                energyProjection: 6,
                fightingSkills: 5
            },
            comicBio: "Cast down to Earth as disabled medical student Donald Blake by his father Odin to learn humility, Thor reclaimed Mjolnir and became a founding member of the Avengers. Later became King of Asgard, wielding the All-Father Thor-Force.",
            mcuBio: "Portrayed by Chris Hemsworth. Endured the tragic loss of his mother, father, brother Loki, and his homeland Asgard. Recovered from severe depression to help defeat Thanos in Endgame, and adopted Gorr's resurrected daughter Love in 'Thor: Love and Thunder'.",
            comicVsMcuDiff: "In comics, Thor went through a profound existential era as 'The Unworthy Thor' after Nick Fury whispered that 'Gorr was right' in his ear, leading Jane Foster to lift Mjolnir as the Mighty Thor for an extended acclaimed run.",
            majorStorylines: ["The Surtur Saga", "Thor: God of Thunder (Gorr)", "The Mighty Thor (Jane Foster)", "Ragnarok", "War of the Realms"],
            tags: ["Thor", "Asgard", "Mjolnir", "God of Thunder", "Stormbreaker", "Avengers"]
        },
        {
            id: "wolverine",
            name: "Logan / James Howlett",
            alias: "Wolverine",
            firstAppearance: "The Incredible Hulk #180-181 (October 1974)",
            creators: "Roy Thomas, Len Wein, John Romita Sr.",
            universe: "Earth-616 & Earth-10005 (Fox) & MCU",
            powers: [
                "Regenerative healing factor recovering from virtually any lethal injury",
                "Skeleton and six retractable claws surgically bonded with indestructible Adamantium",
                "Heightened animalistic senses (tracking scents across miles, night vision)",
                "Immunity to poisons, diseases, and telepathic resistance",
                "Centuries of military, martial arts, and samurai combat expertise"
            ],
            powerGrid: {
                intelligence: 2,
                strength: 4,
                speed: 3,
                durability: 4,
                energyProjection: 1,
                fightingSkills: 6
            },
            comicBio: "Born in 19th-century Canada as James Howlett, Logan lived for decades as a soldier, ronin, and covert operative before being abducted and mutilated by the Weapon X program. Professor X recruited him into the 'All-New, All-Different' X-Men in Giant-Size X-Men #1 (1975).",
            mcuBio: "Portrayed by Hugh Jackman across 24 years of cinema history. Sacrificed himself heroically in 'Logan' (2017). A devastated, guilt-ridden variant returned to save his universe alongside Wade Wilson in 'Deadpool & Wolverine' (2024).",
            comicVsMcuDiff: "In comics, Logan is notably short (5'3\") and stocky, with an extremely gruff, feral personality. Hugh Jackman's tall (6'2\") charismatic interpretation redefined the global image of the character.",
            majorStorylines: ["Weapon X", "Old Man Logan", "Enemy of the State", "Kitty Pryde and Wolverine", "Death of Wolverine"],
            tags: ["Wolverine", "Logan", "X-Men", "Adamantium", "Weapon X", "Mutants"]
        },
        {
            id: "gorr-the-god-butcher",
            name: "Gorr",
            alias: "The God Butcher",
            firstAppearance: "Thor: God of Thunder #1 (January 2013)",
            creators: "Jason Aaron, Esad Ribić",
            universe: "Earth-616",
            powers: [
                "Bonded with All-Black the Necrosword (the first symbiote created by Knull)",
                "Creation of Berserker minions, shadow tendrils, and darkness armor",
                "Strength capable of decapitating Celestials and butchering entire pantheons of gods",
                "Immortality and self-sustenance as long as the blade tastes divine blood"
            ],
            powerGrid: {
                intelligence: 3,
                strength: 6,
                speed: 4,
                durability: 6,
                energyProjection: 6,
                fightingSkills: 5
            },
            comicBio: "Born on a desolate, nameless alien world where his prayers went unanswered as his pregnant wife and starving children died. When he discovered gods were real but simply didn't care, he claimed the Necrosword from Knull and spent three millennia butchering deities across the universe, constructing the 'Godbomb' to kill every god across all of time.",
            mcuBio: "Portrayed by Christian Bale in 'Thor: Love and Thunder'. Wielded the Necrosword to reach Eternity to wish for the extinction of all gods, but chose instead to resurrect his daughter Love before dying.",
            comicVsMcuDiff: "In the comics, Thor had to team up with two temporal variants (Young Thor, Avenger Thor, and Old King Thor with the All-Black) over thousands of years to defeat Gorr. The Necrosword's connection to Knull and the symbiotes was omitted in the MCU.",
            majorStorylines: ["Thor: God of Thunder #1-11 (The God Butcher & Godbomb)"],
            tags: ["Gorr", "God Butcher", "Thor", "Necrosword", "Knull", "All-Black"]
        },
        {
            id: "kang-the-conqueror",
            name: "Nathaniel Richards",
            alias: "Kang the Conqueror",
            firstAppearance: "The Avengers #8 (September 1964)",
            creators: "Stan Lee, Jack Kirby",
            universe: "Earth-616 & Council of Kangs",
            powers: [
                "40th-century technology, time-ship, and temporal armor",
                "Master tactician, temporal engineer, and conqueror of entire centuries",
                "Access to weaponry from every era in past and future history",
                "Infinite variants across the multiverse (Immortus, Rama-Tut, Iron Lad, Scarlet Centurion)"
            ],
            powerGrid: {
                intelligence: 6,
                strength: 3,
                speed: 2,
                durability: 4,
                energyProjection: 4,
                fightingSkills: 4
            },
            comicBio: "A 30th-century scholar and descendant of both Reed Richards and Victor Von Doom, Nathaniel discovered Doctor Doom's time-travel technology and conquered ancient Egypt as Pharaoh Rama-Tut before adopting the warlord identity of Kang the Conqueror.",
            mcuBio: "Introduced via variants in 'Loki' (He Who Remains) and 'Ant-Man and the Wasp: Quantumania' (Kang the Exile).",
            comicVsMcuDiff: "In comics, Kang is renowned for defeating the Avengers repeatedly through patience and honor, even raising Black Bolt's son Ahura.",
            majorStorylines: ["The Kang Dynasty", "Avengers Forever", "Kang War", "Citizen Kang"],
            tags: ["Kang", "Time Travel", "Multiverse", "Avengers", "Rama-Tut", "Immortus"]
        }
    ],

    comicRuns: [
        {
            id: "hickman-avengers",
            title: "Jonathan Hickman's Avengers & Secret Wars",
            years: "2012 - 2015",
            writer: "Jonathan Hickman",
            artists: "Jerome Opeña, Esad Ribić, Dustin Weaver",
            overview: "A grand 3-year masterwork examining the slow death of the multiverse through incursions, the moral degradation of the Illuminati, and the ultimate climax on God Emperor Doom's Battleworld.",
            mustReadIssues: "Avengers (Vol. 5) #1-44, New Avengers (Vol. 3) #1-33, Infinity #1-6, Secret Wars #1-9.",
            bestFor: "Fans anticipating the MCU's 'Avengers: Secret Wars' and 'Avengers: Doomsday'."
        },
        {
            id: "brubaker-captain-america",
            title: "Ed Brubaker's Captain America (Winter Soldier)",
            years: "2005 - 2012",
            writer: "Ed Brubaker",
            artists: "Steve Epting, Michael Lark",
            overview: "Broke a 40-year comic taboo by resurrecting Bucky Barnes as a brainwashed Soviet cybernetic assassin, transforming Captain America into a noir espionage masterclass.",
            mustReadIssues: "Captain America (Vol. 5) #1-25 (Winter Soldier & Death of Captain America).",
            bestFor: "Fans of 'Captain America: The Winter Soldier' film."
        },
        {
            id: "jason-aaron-thor",
            title: "Jason Aaron's Thor: God of Thunder",
            years: "2012 - 2019",
            writer: "Jason Aaron",
            artists: "Esad Ribić, Russell Dauterman",
            overview: "Introduced Gorr the God Butcher, traversed millennia of divine mythology, and chronicled Jane Foster's heroic battle with cancer as the Mighty Thor.",
            mustReadIssues: "Thor: God of Thunder #1-11, The Mighty Thor #1-706, War of the Realms #1-6.",
            bestFor: "Fans wanting grand, mythic storytelling and the true story of Gorr."
        },
        {
            id: "bendis-ultimate-spider-man",
            title: "Brian Michael Bendis's Ultimate Spider-Man",
            years: "2000 - 2011",
            writer: "Brian Michael Bendis",
            artists: "Mark Bagley, Sara Pichelli",
            overview: "Reimagined Peter Parker for the 21st century and later introduced Miles Morales, forever altering modern superhero comics.",
            mustReadIssues: "Ultimate Spider-Man #1-133, Death of Spider-Man, Ultimate Comics Spider-Man #1-28 (Miles debut).",
            bestFor: "Spider-Man fans of all ages and Miles Morales origin seekers."
        }
    ]
};

// Export for module systems or global window access
if (typeof window !== 'undefined') {
    window.MARVEL_DATA = MARVEL_DATA;
}
if (typeof module !== 'undefined' && module.exports) {
    module.exports = MARVEL_DATA;
}
